# Generated by Django 5.0.1 on 2024-01-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_active_user',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_staff_user',
            new_name='is_staff',
        ),
    ]
