# Generated by Django 5.0.1 on 2024-01-19 06:59

from django.db import migrations, models


def update_admin_log(apps, schema_editor):
    """Update user model to enable account deletion"""
    UserAccount = apps.get_model("users", "UserAccount")
    LogEntry = apps.get_model("admin", "LogEntry")

    LogEntry._meta.get_field("user").swappable = True
    LogEntry._meta.get_field("user").model = UserAccount


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_is_active_user_useraccount_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="dummy_field",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RunPython(update_admin_log),
    ]
