# Generated by Django 5.0.1 on 2024-01-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='dummy_field',
        ),
    ]
